### ISSUE TITLE
Release to the Chrome Web Store

### ISSUE THREAD

**Issue by vincentfiestada** [rose-pine/google-chrome#1]
Hi, thanks for creating a great theme! Is there a reason why this plugin hasn't been released to the Chrome Web Store or [Microsoft Edge Add-ons](https://microsoftedge.microsoft.com/addons/)?

**Comment by fvrests** [comment]
Thank you for your kind words! You're right, there's not really a reason it hasn't been posted. I'm working on a Chrome Web store entry and looks like Edge should be pretty straightforward to support too. Hopefully this should decrease some friction to install when completed. ☺️

**Comment by cutbypham** [comment]
- I just manual publish the theme on chrome webstore by myself.
- I think good to be use github workflows for auto publish on webstore (https://docs.plasmo.com/framework/workflows/submit)

**Themes**
- https://chrome.google.com/webstore/detail/ros%C3%A9-pine/noimedcjdohhokijigpfcbjcfcaaahej
- https://chrome.google.com/webstore/detail/ros%C3%A9-pine-moon/ohjebgkppidheiajbgnnmmieaapjppje
- https://chrome.google.com/webstore/detail/ros%C3%A9-pine-dawn/faffeempkcpjhcmfpglpkdpbkdmbpaab

**Comment by mvllow** [comment]
Thank you @thuanowa, I added you as a maintainer so feel free to add a workflow or any other changes if you have time 💜
