### ISSUE TITLE
new tab page in the theme 

### ISSUE THREAD

**Issue by kanishkaverma** [rose-pine/google-chrome#2]
Hey, 
Love the theme. I was wondering what is the new tab extension called for the screenshots of this theme in the read me. 
Thank you.

**Comment by fvrests** [comment]
Glad you're enjoying the theme! The new tab extension is [lavender](https://chrome.google.com/webstore/detail/lavender-new-tab/ffobepdbanoiodmfimpmanafepclokbc) 😌
