### ISSUE TITLE
[Discussion] [Dawn] Better contrast active tab

### ISSUE THREAD

**Issue by cutbypham** [rose-pine/google-chrome#3]
**"theme_toolbar": "swatches/ffffff.png"**
![image](https://user-images.githubusercontent.com/40050527/224007025-c9480ed5-7443-468c-9270-79a67a0360d7.png)

**version 2.0.0**
![image](https://user-images.githubusercontent.com/40050527/224007161-65fd2035-cec1-485f-87bb-1f72fec1ebae.png)

**rp-dawn-surface vs #ffffff**
![image](https://user-images.githubusercontent.com/40050527/224007062-903ad64b-5613-461c-83da-3d2a648b8253.png)

- I have hard time to distinguish between non-active tab vs. active tab
- Anyone has ideas?

**Comment by mvllow** [comment]
We've used overlay or our highlight (med/high) palette colours in the past for active backgrounds if any of those look better :)

If I remember correctly, the colours in Chrome do not always match the hex code for some reason.

**Comment by fvrests** [comment]
<img width="724" alt="Screenshot 2023-03-09 at 1 15 02 PM" src="https://user-images.githubusercontent.com/47515065/224130892-153461f1-a134-4e00-86c2-793b2261f5bc.png">
@thuanowa Thanks for bringing this up! See #4, I'm open to alternatives but will merge this now to improve contrast as I think it does help quite a bit.
